select
    productid as product_id,
    name as product_name,
    productnumber as product_number,
    makeflag as is_manufactured_in_house,
    finishedgoodsflag as is_finished_good,
    color,
    safetystocklevel as safety_stock_level,
    reorderpoint as reorder_point,
    standardcost as standard_cost,
    listprice as list_price,
    size,
    sizeunitmeasurecode as size_unit_measure_code,
    weightunitmeasurecode as weight_unit_measure_code,
    weight,
    daystomanufacture as days_to_manufacture,
    productline as product_line,
    class,
    style,
    productsubcategoryid as product_subcategory_id,
    productmodelid as product_model_id,
    sellstartdate::date as sell_start_date,
    sellenddate::date as sell_end_date,
    discontinueddate::date as discontinued_date,
    rowguid,
    modifieddate as modified_at
from {{ source('oltp_production', 'product') }}
