name: adventureworks_analytics
version: "1.0.0"
config-version: 2

profile: adventureworks_analytics

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  adventureworks_analytics:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core_dw
      +materialized: table
    marts:
      +enabled: false
      sales:
        +enabled: true
        +schema: mart_sales
        +materialized: table
      finance:
        +enabled: true
        +schema: mart_finance
        +materialized: table
      customer:
        +enabled: true
        +schema: mart_customer
        +materialized: table
      product:
        +enabled: true
        +schema: mart_product
        +materialized: table
      forecast:
        +enabled: true
        +schema: mart_sales_forecast
        +materialized: table
    features:
      +schema: analytics
      +materialized: table
      +enabled: true
    audit:
      +schema: audit
      +materialized: table
